version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        data_type: integer
      - name: status
        tests:
          - accepted_values:
              values:
                - completed
                - placed
                - return_pending
                - returned
                - shipped
        data_type: varchar
        description: "{{ doc('orders_status') }}"
      - name: customer_id
        description: id  of customer
        data_type: integer
        tests:
          - not_null
      - name: order_date
        data_type: date

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: [ 'credit_card', 'coupon', 'bank_transfer', 'gift_card' ]
